name: deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the website
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          sleep 5
          ssh -vvv -i ~/.ssh/staging.key -o StrictHostKeyChecking=no -o ConnectTimeout=180 $SSH_USER@$SSH_HOST 'cd ~ && git pull origin main'
